services:
  app:
    image: todo-front-dev
    volumes:
      - ./todo-frontend/:/usr/src/app
      
  server:
      image: todo-back-dev
      volumes:
        - ./todo-backend/:/usr/src/app
      environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/the_database
      - MONGO_USER=root
      - MONGO_PASS=example
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
  
  mongo:
    image: initialized-mongo
    ports:
      - "3456:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data

volumes:
  mongo_data: